server:
  port: 8017
  
  
spring:
  thymeleaf:
    cache: false # Enable template caching.
#    check-template: true # Check that the template exists before rendering it.
#    check-template-location: true # Check that the templates location exists.
#    enabled: true # Enable Thymeleaf view resolution for Web frameworks.
    encoding: UTF-8 # Template files encoding.
#    excluded-view-names: # Comma-separated list of view names that should be excluded from resolution.
    mode: HTML5 # Template mode to be applied to templates. See also StandardTemplateModeHandlers.
    prefix: classpath:/templates/ # Prefix that gets prepended to view names when building a URL.
##    reactive.max-chunk-size: # Maximum size of data buffers used for writing to the response, in bytes.
#    reactive.media-types: # Media types supported by the view technology.
#    servlet.content-type: text/html # Content-Type value written to HTTP responses.
    suffix: .html # Suffix that gets appended to view names when building a URL.
#    template-resolver-order: # Order of the template resolver in the chain.
#    view-names: # Comma-separated list of view names that can be resolved.


  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pns?characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  tomcat:
    test-on-borrow: true
    validation-query: SELECT 1
    validation-interval: 30000